package com.vasileff.ceylon.dart.compiler;

public enum Warning {
    filenameNonAscii,
    filenameCaselessCollision,
    deprecation,
    disjointEquals,
    disjointContainment,
    compilerAnnotation,
    doclink,
    expressionTypeNothing,
    unusedDeclaration,
    unusedImport,
    ceylonNamespace,
    javaNamespace,
    suppressedAlready,
    suppressesNothing,
    unknownWarning,
    ambiguousAnnotation,
    similarModule,
    importsOtherJdk,
    javaAnnotationElement,
    syntaxDeprecation,
    smallIgnored,
    literalNotSmall,
    redundantNarrowing,
    redundantIteration,
    missingImportPrefix,
    uncheckedTypeArguments,
    expressionTypeCallable,
    uncheckedType
}
