cp -a modules/dart.async-1.2.1-dartmodel.json           ../ceylon-dart-language/modules-dart/dart/async/1.2.1
cp -a modules/dart.collection-1.2.1-dartmodel.json      ../ceylon-dart-language/modules-dart/dart/collection/1.2.1
cp -a modules/dart.convert-1.2.1-dartmodel.json         ../ceylon-dart-language/modules-dart/dart/convert/1.2.1
cp -a modules/dart.core-1.2.1-dartmodel.json            ../ceylon-dart-language/modules-dart/dart/core/1.2.1
cp -a modules/dart.developer-1.2.1-dartmodel.json       ../ceylon-dart-language/modules-dart/dart/developer/1.2.1
cp -a modules/dart.io-1.2.1-dartmodel.json              ../ceylon-dart-language/modules-dart/dart/io/1.2.1
cp -a modules/dart.isolate-1.2.1-dartmodel.json         ../ceylon-dart-language/modules-dart/dart/isolate/1.2.1
cp -a modules/dart.math-1.2.1-dartmodel.json            ../ceylon-dart-language/modules-dart/dart/math/1.2.1
cp -a modules/dart.mirrors-1.2.1-dartmodel.json         ../ceylon-dart-language/modules-dart/dart/mirrors/1.2.1
cp -a modules/dart.typed_data-1.2.1-dartmodel.json      ../ceylon-dart-language/modules-dart/dart/typed_data/1.2.1
